modLoader="javafml" 
loaderVersion="[43,)" 
license="MIT"

[[mods]] 
modId="polypower" 
version="1.0.1 Alpha" 
displayName="Polypower" 
logoFile="logo.png"
authors="Fitaroz"
description='''
PolyPower will be a comprehensive and innovative mod for Minecraft, designed to transform your gaming experience into a diverse and versatile world of energy. The mod will offer a wide range of features, from advanced wireless cables to various energy storage and generation systems. One of the main aspects of this mod will be the promotion of green and clean energies, thus fostering sustainable and environmentally-friendly gameplay. Players will be able to harness and use renewable energy sources such as solar and hydro power to power their facilities and enhance their virtual world responsibly. In addition, PolyPower will integrate advanced wireless cables to reduce FPS losses caused by traditional cables. These wireless cables will offer an efficient solution for transmitting power across your world, enhancing game performance and ensuring a smooth gaming experience while promoting efficient and environmentally-friendly energy management.
'''
[[dependencies.polypower]]

    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.polypower]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
